### ISSUE TITLE
Feature - Check the existence of Pull Request Template

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-api#22]
**What is needed**
According to the [Measurement Model](https://fga-eps-mds.github.io/2019.1-hubcare-docs/project-quality-management/measurement-model/), the API needs to check if some Pull Request Template exists.

**Acceptance criteria**
- [ ] Return if at least one Pull Request Template exists

**Comment by vitorAlves7** [comment]
I'm having difficulty finding PULL_REQUEST_TEMPLATE.md.
Because when looking for the url in the github API in some repositories the link to the file can be found at 'https://api.github.com/repos/' + owner + '/' + repo + '/contents/.github
and in another the paths are https://api.github.com/repos/ '+ owner +' / '+ repo +' / contents
and the file name is different, such as pull_request_template.md or Pull_Request_Template.md.

**Comment by cjjcastro** [comment]
I believe you have already answered your question. The two URLs are valid for this case, check both, and check the file name of both forms.
